import { Country } from '../../types/application/AppControll';

export const Countries: Country[] = [
  {
    name: 'Albania',
    leagues: [
      { name: 'Superliga' },
      { name: 'First Division' },
      { name: 'Second Division' },
    ],
  },
  { name: 'Algeria', leagues: [{ name: 'Ligue 2' }, { name: 'Ligue 1' }] },
  { name: 'Andorra', leagues: [{ name: 'Segona Divisió' }] },
  { name: 'Angola', leagues: [{ name: 'Girabola' }] },
  {
    name: 'Argentina',
    leagues: [
      { name: 'Prim B Nacional' },
      { name: 'Primera División' },
      { name: 'Reserve League' },
      { name: 'Prim B Metro' },
    ],
  },
  { name: 'Armenia', leagues: [{ name: 'First League' }] },
  { name: 'Aruba', leagues: [{ name: 'Division di Honor' }] },
  {
    name: 'Australia',
    leagues: [
      { name: 'Northern NSW Reserve League' },
      { name: 'Victoria NPL Youth League' },
      { name: 'Victoria NPL 2 Youth' },
      { name: 'Capital Territory NPL Youth League' },
      { name: 'New South Wales NPL Youth League' },
      { name: 'South Australia State League 1 Reserves' },
      { name: 'A-League' },
      { name: 'Capital Territory NPL' },
      { name: 'Capital Territory NPL 2' },
      { name: 'Victoria NPL 2' },
      { name: 'Victoria NPL 3' },
      { name: 'Victoria NPL Women' },
      { name: 'Northern NSW NPL' },
      { name: 'Northern NSW State League 1' },
      { name: 'Victoria NPL' },
      { name: 'New South Wales NPL' },
      { name: 'South Australia NPL' },
      { name: 'South Australia State League 1' },
      { name: 'Queensland NPL Youth League' },
      { name: 'New South Wales NPL 2' },
      { name: 'Queensland NPL' },
      { name: 'Queensland Premier League 2' },
      { name: 'Queensland Premier League' },
      { name: 'Queensland NPL Women' },
      { name: 'New South Wales NPL 3' },
    ],
  },
  {
    name: 'Austria',
    leagues: [
      { name: '2. Liga' },
      { name: 'Regionalliga' },
      { name: 'Landesliga Kärnten' },
      { name: 'Landesliga Vorarlberg' },
      { name: 'Landesliga Tirol' },
      { name: 'Bundesliga' },
    ],
  },
  { name: 'Azerbaijan', leagues: [{ name: 'Premyer Liqası' }] },
  { name: 'Bahrain', leagues: [{ name: 'Bahraini Premier League' }] },
  {
    name: 'Bangladesh',
    leagues: [{ name: 'Bangladesh Football Premier League' }],
  },
  { name: 'Belarus', leagues: [{ name: 'Vysheyshaya Liga' }] },
  {
    name: 'Belgium',
    leagues: [
      { name: '1st National Women' },
      { name: 'First Division B' },
      { name: 'Second Amateur Division : VFV B' },
      { name: 'Pro League' },
      { name: 'First Amateur Division' },
      { name: 'Second Amateur Division : VFV A' },
      { name: 'Second Amateur Division : ACFF' },
    ],
  },
  { name: 'Benin', leagues: [{ name: 'Championnat National' }] },
  { name: 'Bermuda', leagues: [{ name: 'Bermudian Premier Division' }] },
  { name: 'Bolivia', leagues: [{ name: 'LFPB' }] },
  {
    name: 'Bosnia and Herzegovina',
    leagues: [
      { name: 'Premier League of Bosnia' },
      { name: 'First League RS' },
      { name: 'First League FBiH' },
    ],
  },
  { name: 'Botswana', leagues: [{ name: 'Botswana Premier League' }] },
  {
    name: 'Brazil',
    leagues: [
      { name: 'Capixaba' },
      { name: 'Serie B' },
      { name: 'Carioca U20' },
      { name: 'Serie C' },
      { name: 'Paulista A3' },
      { name: 'Brasiliense' },
      { name: 'Piauiense' },
      { name: 'Paulista A2' },
      { name: 'Sergipano' },
      { name: 'Alagoano' },
      { name: 'Serie A' },
      { name: 'Rondoniense' },
      { name: 'Acreano' },
      { name: 'Roraimense' },
    ],
  },
  {
    name: 'Bulgaria',
    leagues: [
      { name: 'Second League' },
      { name: 'Womens League' },
      { name: 'Third League Northeast' },
      { name: 'Elite U19' },
      { name: 'Third League Northwest' },
      { name: 'Third League Southwest' },
      { name: 'Third League Southeast' },
      { name: 'First League' },
    ],
  },
  { name: 'Burkina Faso', leagues: [{ name: 'Burkinabé Premier League' }] },
  { name: 'Burundi', leagues: [{ name: 'Burundi Premier League' }] },
  { name: 'Canada', leagues: [{ name: 'Canadian Premier League' }] },
  {
    name: 'Chile',
    leagues: [{ name: 'Primera B' }, { name: 'Primera División' }],
  },
  {
    name: 'Colombia',
    leagues: [{ name: 'Categoria Primera B' }, { name: 'Categoria Primera A' }],
  },
  { name: 'Congo', leagues: [{ name: 'Congo Premier League' }] },
  { name: 'Costa Rica', leagues: [{ name: 'Primera División FPD' }] },
  {
    name: 'Croatia',
    leagues: [
      { name: 'Prva HNL Juniori' },
      { name: '3. HNL West' },
      { name: '3. HNL North' },
      { name: 'Druga HNL' },
      { name: '3. HNL South' },
      { name: '3. HNL Center' },
      { name: '3. HNL East' },
      { name: 'Prva HNL' },
    ],
  },
  {
    name: 'Cyprus',
    leagues: [
      { name: 'Second Division' },
      { name: '3. Division' },
      { name: 'First Division' },
    ],
  },
  {
    name: 'Czech Republic',
    leagues: [
      { name: '4. Liga Division D' },
      { name: '3. Liga MSFL CFL' },
      { name: '1. Liga U19' },
      { name: '4. Liga Division B' },
      { name: '4. Liga Division A' },
      { name: '4. Liga Division C' },
      { name: 'FNL' },
      { name: '4. Liga Division F' },
      { name: '4. Liga Division E' },
      { name: 'First League' },
    ],
  },
  {
    name: 'Denmark',
    leagues: [
      { name: 'Denmark Series Group 2' },
      { name: 'U19 Ligaen' },
      { name: 'Denmark Series Group 1' },
      { name: 'Denmark Series Group 3' },
      { name: 'Denmark Series Group 4' },
      { name: '1st Division' },
      { name: '3. Division' },
      { name: '2nd Division' },
    ],
  },
  { name: 'Djibouti', leagues: [{ name: 'Division 1' }] },
  { name: 'Ecuador', leagues: [{ name: 'Primera Categoría Serie A' }] },
  { name: 'Egypt', leagues: [{ name: 'Egyptian Premier League' }] },
  { name: 'El Salvador', leagues: [{ name: 'Reserve League' }] },
  {
    name: 'England',
    leagues: [
      { name: 'Youth Alliance' },
      { name: 'U18 Premier League' },
      { name: 'Premier League' },
      { name: 'Championship' },
      { name: 'Isthmian League South Central Division' },
      { name: 'EFL League Two' },
      { name: 'EFL League One' },
      { name: 'National League North and South' },
      { name: 'National League' },
      { name: 'Isthmian Premier Division' },
      { name: 'Isthmian League Division One North' },
      { name: 'Southern League Division One Central' },
      { name: 'Northern Premier League' },
      { name: 'Southern League Premier Central' },
      { name: 'Southern League Premier South' },
      { name: 'Isthmian League South East Division' },
      { name: 'Northern East Division One' },
      { name: 'Northern Midlands Division One' },
      { name: 'Northern West Division One' },
      { name: 'Southern South Division One' },
      { name: 'Counties Leagues Essex Senior League' },
      { name: 'Counties Leagues Combined Counties Premier North' },
      { name: 'Counties Leagues Combined Counties Premier South' },
      { name: 'Counties Leagues Eastern Counties League' },
      { name: 'Counties Leagues Midland League Premier' },
      { name: 'Counties Leagues Northern Counties East' },
      { name: 'Counties Leagues Northern League One' },
      { name: 'Counties Leagues Southern Combination League Premier' },
    ],
  },
  {
    name: 'Esports',
    leagues: [{ name: 'Esoccer Liga Pro' }, { name: 'Esoccer Battle' }],
  },
  {
    name: 'Estonia',
    leagues: [
      { name: 'Esiliiga' },
      { name: 'Esiliiga B' },
      { name: 'Meistriliiga' },
    ],
  },
  {
    name: 'Faroe Islands',
    leagues: [
      { name: '2. Deild' },
      { name: '1. Deild' },
      { name: 'Faroe Islands Premier League' },
    ],
  },
  { name: 'Fiji', leagues: [{ name: 'National Football League' }] },
  {
    name: 'Finland',
    leagues: [
      { name: 'A Junior League' },
      { name: 'Finnish Cup' },
      { name: 'Veikkausliiga' },
    ],
  },
  {
    name: 'France',
    leagues: [
      { name: 'Championnat National U19' },
      { name: 'National 3 Group D' },
      { name: 'Ligue 2' },
      { name: 'National 3 Group C' },
      { name: 'National 3 Group F' },
      { name: 'National 3 Group I' },
      { name: 'National 2 Group C' },
      { name: 'National 3 Group M' },
      { name: 'National 3 Group J' },
      { name: 'Ligue 1' },
      { name: 'National 2 Group B' },
      { name: 'National 3 Group L' },
      { name: 'National 3 Group B' },
      { name: 'National' },
      { name: 'National 2 Group A' },
      { name: 'National 2 Group D' },
      { name: 'National 3 Group E' },
      { name: 'National 3 Group K' },
      { name: 'National 3 Group A' },
      { name: 'National 3 Group H' },
    ],
  },
  { name: 'FYR Macedonia', leagues: [{ name: 'Second Football League' }] },
  { name: 'Gambia', leagues: [{ name: 'GFA League' }] },
  {
    name: 'Germany',
    leagues: [
      { name: 'U19 Bundesliga' },
      { name: 'Regionalliga Nordost' },
      { name: 'Oberliga Bremen' },
      { name: 'Oberliga Nordost Nord' },
      { name: 'Regionalliga Nord' },
      { name: '2. Bundesliga' },
      { name: 'Regionalliga Bayern' },
      { name: '3. Liga' },
      { name: 'Oberliga Bayern Nord' },
      { name: 'Oberliga Bayern Süd' },
      { name: 'Oberliga Nordost Süd' },
      { name: 'Oberliga Baden Wurttemberg' },
      { name: 'Regionalliga Südwest' },
      { name: 'Regionalliga West' },
      { name: 'Bundesliga' },
    ],
  },
  { name: 'Ghana', leagues: [{ name: 'Ghana Premier League' }] },
  { name: 'Gibraltar', leagues: [{ name: 'Premier Division' }] },
  {
    name: 'Greece',
    leagues: [
      { name: 'Super League K19' },
      { name: 'Super League 2' },
      { name: 'Gamma Ethniki Group 5' },
      { name: 'Super League' },
    ],
  },
  { name: 'Guadeloupe', leagues: [{ name: 'Guadeloupe Division of Honor' }] },
  {
    name: 'Guatemala',
    leagues: [
      { name: 'Primera División de Ascenso' },
      { name: 'Liga Nacional de Fútbol de Guatemala' },
    ],
  },
  { name: 'Hong Kong', leagues: [{ name: 'Sapling Cup' }] },
  {
    name: 'Hungary',
    leagues: [
      { name: 'U19 League' },
      { name: 'U19 Playoffs' },
      { name: 'U19 Alap' },
      { name: 'NB I' },
      { name: 'NB III Kozep' },
      { name: 'NB III Nyugati' },
    ],
  },
  { name: 'Iceland', leagues: [{ name: 'Iceland Cup' }] },
  { name: 'India', leagues: [{ name: 'I-League' }] },
  { name: 'Iran', leagues: [{ name: 'Hazfi Cup' }] },
  {
    name: 'Israel',
    leagues: [
      { name: 'U19 Elite Division' },
      { name: 'Israeli Premier League' },
    ],
  },
  {
    name: 'Italy',
    leagues: [
      { name: 'Campionato Primavera 1' },
      { name: 'Campionato Primavera 2' },
      { name: 'Campionato Primavera 4' },
      { name: 'Serie B' },
      { name: 'Serie C Group B' },
      { name: 'Serie C Group C' },
      { name: 'Campionato Primavera 3' },
      { name: 'Serie A' },
      { name: 'Serie D Group C' },
      { name: 'Serie D Group B' },
      { name: 'Serie D Group G' },
      { name: 'Primavera Women' },
    ],
  },
  { name: 'Ivory Coast', leagues: [{ name: 'Ivory Coast Ligue 1' }] },
  {
    name: 'Japan',
    leagues: [
      { name: 'J2 League' },
      { name: 'Japan Football League' },
      { name: 'Nadeshiko League 1' },
      { name: 'Nadeshiko League 2' },
      { name: 'J1 League' },
    ],
  },
  { name: 'Jordan', leagues: [{ name: 'Jordanian Pro League' }] },
  { name: 'Kazakhstan', leagues: [{ name: 'Kazakhstan Premier League' }] },
  { name: 'Kenya', leagues: [{ name: 'Kenyan Premier League' }] },
  { name: 'Kosovo', leagues: [{ name: 'Superleague of Kosovo' }] },
  { name: 'Kuwait', leagues: [{ name: 'Kuwait Premier League' }] },
  { name: 'Lebanon', leagues: [{ name: 'Lebanese Premier League' }] },
  { name: 'Lesotho', leagues: [{ name: 'Lesotho Premier League' }] },
  { name: 'Lithuania', leagues: [{ name: 'A Lyga' }] },
  {
    name: 'Malaysia',
    leagues: [{ name: 'Malaysia Premier League' }, { name: 'Super League' }],
  },
  { name: 'Maldives', leagues: [{ name: 'Dhivehi Premier League' }] },
  {
    name: 'Malta',
    leagues: [
      { name: 'First Division' },
      { name: 'Gozo First Division' },
      { name: 'Maltese Premier League' },
    ],
  },
  { name: 'Mauritania', leagues: [{ name: 'Super D1' }] },
  {
    name: 'Mexico',
    leagues: [
      { name: 'Liga MX' },
      { name: 'Liga Premier Serie A' },
      { name: 'U20 League' },
      { name: 'Liga Premier Serie B' },
    ],
  },
  {
    name: 'Moldova',
    leagues: [{ name: 'Moldovan National Division' }, { name: 'Division A' }],
  },
  { name: 'Mongolia', leagues: [{ name: 'Mongolian Premier League' }] },
  { name: 'Montenegro', leagues: [{ name: 'Montenegrin Second League' }] },
  {
    name: 'Morocco',
    leagues: [{ name: 'Botola 2' }, { name: 'Division 1 Féminin' }],
  },
  {
    name: 'Netherlands',
    leagues: [
      { name: 'U21 Divisie 4' },
      { name: 'U21 Divisie 3' },
      { name: 'U21 Divisie 1' },
      { name: 'Tweede Divisie' },
      { name: 'Derde Divisie - Zaterdag' },
      { name: 'U21 Divisie 2' },
      { name: 'Eredivisie' },
    ],
  },
  {
    name: 'Nicaragua',
    leagues: [{ name: 'Liga Primera U20' }, { name: 'Primera Division' }],
  },
  {
    name: 'Northern Ireland',
    leagues: [
      { name: 'Premiership Development League' },
      { name: 'Premier Intermediate League' },
      { name: 'NIFL Championship' },
      { name: 'NIFL Premiership' },
    ],
  },
  {
    name: 'Norway',
    leagues: [
      { name: '3. Division Group 1' },
      { name: '3. Division Group 2' },
      { name: '3. Division Group 6' },
      { name: '2. Division' },
      { name: '3. Division Group 3' },
      { name: '3. Division Group 4' },
      { name: '3. Division Group 5' },
      { name: 'Eliteserien' },
      { name: 'First Division' },
    ],
  },
  { name: 'Palestine', leagues: [{ name: 'West Bank League' }] },
  { name: 'Panama', leagues: [{ name: 'Liga Prom' }, { name: 'LPF' }] },
  {
    name: 'Paraguay',
    leagues: [
      { name: 'Division Intermedia' },
      { name: 'Division Profesional' },
    ],
  },
  { name: 'Peru', leagues: [{ name: 'Primera División' }] },
  {
    name: 'Poland',
    leagues: [
      { name: '3. Liga' },
      { name: 'Central Youth League' },
      { name: '1. Liga' },
      { name: 'Ekstraklasa' },
      { name: '2. Liga' },
    ],
  },
  {
    name: 'Portugal',
    leagues: [
      { name: 'LigaPro' },
      { name: 'U19 League' },
      { name: 'Liga 3' },
      { name: 'Liga NOS' },
    ],
  },
  {
    name: 'Republic of Ireland',
    leagues: [{ name: 'First Division' }, { name: 'Premier Division' }],
  },
  {
    name: 'Romania',
    leagues: [
      { name: 'U19 League' },
      { name: 'Liga II' },
      { name: '3. Liga Series 5' },
      { name: '3. Liga Series 4' },
      { name: '3. Liga Series 1' },
      { name: '3. Liga Series 2' },
      { name: '3. Liga Series 7' },
      { name: '3. Liga Series 6' },
      { name: '3. Liga Series 9' },
      { name: '3. Liga Series 10' },
      { name: '3. Liga Series 8' },
      { name: '3. Liga Series 3' },
      { name: 'Liga I' },
    ],
  },
  { name: 'Russia', leagues: [{ name: 'Russian Premier League' }] },
  { name: 'San Marino', leagues: [{ name: 'Campionato Sammarinese' }] },
  { name: 'Saudi Arabia', leagues: [{ name: 'Youth League' }] },
  {
    name: 'Scotland',
    leagues: [
      { name: 'Feeder Leagues' },
      { name: 'League Two' },
      { name: 'League One' },
      { name: 'Championship' },
      { name: 'Premiership' },
      { name: 'Highland / Lowland Football Leagues' },
    ],
  },
  { name: 'Senegal', leagues: [{ name: 'Senegal Premier League' }] },
  {
    name: 'Serbia',
    leagues: [
      { name: 'Srpska Liga Belgrade' },
      { name: 'U19 League' },
      { name: 'Srpska Liga West' },
      { name: 'SuperLiga' },
      { name: 'Prva Liga' },
      { name: 'Srpska Liga Vojvodina' },
      { name: 'Srpska Liga East' },
    ],
  },
  {
    name: 'Sierra Leone',
    leagues: [{ name: 'Sierra Leone National Premier League' }],
  },
  { name: 'Singapore', leagues: [{ name: 'S.League' }] },
  {
    name: 'Slovakia',
    leagues: [
      { name: '3. Liga' },
      { name: 'U19 League' },
      { name: '2. Liga' },
      { name: 'Super Liga' },
    ],
  },
  {
    name: 'Slovenia',
    leagues: [{ name: '2. SNL' }, { name: 'PrvaLiga' }, { name: '3. SNL' }],
  },
  { name: 'South Africa', leagues: [{ name: 'South African Cup' }] },
  {
    name: 'South Korea',
    leagues: [
      { name: 'K4 League' },
      { name: 'K League 1' },
      { name: 'K3 League' },
      { name: 'K League 2' },
    ],
  },
  {
    name: 'Spain',
    leagues: [
      { name: 'División de Honor Juvenil' },
      { name: 'Tercera Group 4' },
      { name: 'Tercera Group 9' },
      { name: 'Tercera Group 10' },
      { name: 'Tercera Group 7' },
      { name: 'La Liga' },
      { name: 'Segunda División' },
      { name: 'Segunda División RFEF' },
      { name: 'Tercera Group 3' },
      { name: 'Tercera Group 6' },
      { name: 'Tercera Group 11' },
      { name: 'Tercera Group 15' },
      { name: 'Segunda División B' },
      { name: 'Tercera Group 1' },
      { name: 'Tercera Group 2' },
      { name: 'Tercera Group 5' },
      { name: 'Tercera Group 8' },
      { name: 'Tercera Group 12' },
      { name: 'Tercera Group 13' },
      { name: 'Tercera Group 18' },
      { name: 'Tercera Group 14' },
      { name: 'Tercera Group 16' },
      { name: 'Tercera Group 17' },
    ],
  },
  { name: 'Sudan', leagues: [{ name: 'Sudani Premier League' }] },
  {
    name: 'Sweden',
    leagues: [
      { name: 'Division 2: Norrland' },
      { name: 'Division 2: Vastra Gotaland' },
      { name: 'U19 League' },
      { name: 'Superettan' },
      { name: 'Division 1' },
      { name: 'Division 2: Norra Gotaland' },
      { name: 'Division 2: Norra Svealand' },
      { name: 'Division 2: Sodra Gotaland' },
      { name: 'Division 2: Sodra Svealand' },
      { name: 'Elitettan Women' },
      { name: 'Allsvenskan' },
    ],
  },
  {
    name: 'Switzerland',
    leagues: [
      { name: '1. Liga Promotion' },
      { name: '1. Liga Classic' },
      { name: 'Challenge League' },
      { name: 'Super League' },
    ],
  },
  { name: 'Syria', leagues: [{ name: 'Syrian Premier League' }] },
  { name: 'Tahiti', leagues: [{ name: 'Tahitian Ligue 1' }] },
  { name: 'Tajikistan', leagues: [{ name: 'Vysshaya Liga' }] },
  {
    name: 'Thailand',
    leagues: [{ name: 'Thai League 2' }, { name: 'Thai League T1' }],
  },
  {
    name: 'Turkey',
    leagues: [
      { name: 'U19 Süper Lig' },
      { name: 'U19 1. Lig' },
      { name: '3. Lig Group 2' },
      { name: 'Süper Lig' },
      { name: '1. Lig' },
      { name: '2 Lig Kirmizi' },
      { name: '2 Lig Beyaz' },
    ],
  },
  { name: 'UAE', leagues: [{ name: 'Division One' }] },
  { name: 'Uganda', leagues: [{ name: 'Uganda Premier League' }] },
  { name: 'Ukraine', leagues: [{ name: 'Persha Liga' }] },
  { name: 'Uruguay', leagues: [{ name: 'Primera División' }] },
  {
    name: 'USA',
    leagues: [
      { name: 'USL League One' },
      { name: 'MLS' },
      { name: 'USL Championship' },
    ],
  },
  { name: 'Venezuela', leagues: [{ name: 'Primera División' }] },
  { name: 'Vietnam', leagues: [{ name: 'Vietnam Cup' }] },
  {
    name: 'Wales',
    leagues: [
      { name: 'FAW Championship' },
      { name: 'Welsh Premier League' },
      { name: 'Welsh Premier Womens League' },
    ],
  },
  { name: 'Zambia', leagues: [{ name: 'Super League' }] },
  { name: 'Zimbabwe', leagues: [{ name: 'Premier Soccer League' }] },
];

export default { Countries };
