/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Bet = {
    OverZeroFive: 'OVER_ZERO_FIVE',
    OverOneFive: 'OVER_ONE_FIVE',
    OverTwoFive: 'OVER_TWO_FIVE',
    HomeWin: 'HOME_WIN',
    AwayWin: 'AWAY_WIN',
    BttsYes: 'BTTS_YES',
    BttsNo: 'BTTS_NO'
} as const;
export type Bet = typeof Bet[keyof typeof Bet];


export function BetFromJSON(json: any): Bet {
    return BetFromJSONTyped(json, false);
}

export function BetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bet {
    return json as Bet;
}

export function BetToJSON(value?: Bet | null): any {
    return value as any;
}

