/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetForMatch
 */
export interface BetForMatch {
    /**
     * 
     * @type {string}
     * @memberof BetForMatch
     */
    placedBet?: BetForMatchPlacedBetEnum;
    /**
     * 
     * @type {boolean}
     * @memberof BetForMatch
     */
    won?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BetForMatch
     */
    evaluated?: boolean;
}


/**
 * @export
 */
export const BetForMatchPlacedBetEnum = {
    OverZeroFive: 'OVER_ZERO_FIVE',
    OverOneFive: 'OVER_ONE_FIVE',
    OverTwoFive: 'OVER_TWO_FIVE',
    HomeWin: 'HOME_WIN',
    AwayWin: 'AWAY_WIN',
    BttsYes: 'BTTS_YES',
    BttsNo: 'BTTS_NO'
} as const;
export type BetForMatchPlacedBetEnum = typeof BetForMatchPlacedBetEnum[keyof typeof BetForMatchPlacedBetEnum];


/**
 * Check if a given object implements the BetForMatch interface.
 */
export function instanceOfBetForMatch(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetForMatchFromJSON(json: any): BetForMatch {
    return BetForMatchFromJSONTyped(json, false);
}

export function BetForMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetForMatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'placedBet': !exists(json, 'placedBet') ? undefined : json['placedBet'],
        'won': !exists(json, 'won') ? undefined : json['won'],
        'evaluated': !exists(json, 'evaluated') ? undefined : json['evaluated'],
    };
}

export function BetForMatchToJSON(value?: BetForMatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'placedBet': value.placedBet,
        'won': value.won,
        'evaluated': value.evaluated,
    };
}

