/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Bet } from './Bet';
import {
    BetFromJSON,
    BetFromJSONTyped,
    BetToJSON,
} from './Bet';

/**
 * 
 * @export
 * @interface BetPredictionQualityBetAggregate
 */
export interface BetPredictionQualityBetAggregate {
    /**
     * 
     * @type {Bet}
     * @memberof BetPredictionQualityBetAggregate
     */
    bet?: Bet;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityBetAggregate
     */
    betSucceeded?: number;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityBetAggregate
     */
    betFailed?: number;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityBetAggregate
     */
    predictionPercent?: number;
}

/**
 * Check if a given object implements the BetPredictionQualityBetAggregate interface.
 */
export function instanceOfBetPredictionQualityBetAggregate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetPredictionQualityBetAggregateFromJSON(json: any): BetPredictionQualityBetAggregate {
    return BetPredictionQualityBetAggregateFromJSONTyped(json, false);
}

export function BetPredictionQualityBetAggregateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetPredictionQualityBetAggregate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bet': !exists(json, 'bet') ? undefined : BetFromJSON(json['bet']),
        'betSucceeded': !exists(json, 'betSucceeded') ? undefined : json['betSucceeded'],
        'betFailed': !exists(json, 'betFailed') ? undefined : json['betFailed'],
        'predictionPercent': !exists(json, 'predictionPercent') ? undefined : json['predictionPercent'],
    };
}

export function BetPredictionQualityBetAggregateToJSON(value?: BetPredictionQualityBetAggregate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bet': BetToJSON(value.bet),
        'betSucceeded': value.betSucceeded,
        'betFailed': value.betFailed,
        'predictionPercent': value.predictionPercent,
    };
}

