/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetPredictionQualityInfluencerAggregate
 */
export interface BetPredictionQualityInfluencerAggregate {
    /**
     * 
     * @type {string}
     * @memberof BetPredictionQualityInfluencerAggregate
     */
    influencerName?: string;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityInfluencerAggregate
     */
    predictionPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityInfluencerAggregate
     */
    betSucceeded?: number;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityInfluencerAggregate
     */
    betFailed?: number;
    /**
     * 
     * @type {number}
     * @memberof BetPredictionQualityInfluencerAggregate
     */
    count?: number;
}

/**
 * Check if a given object implements the BetPredictionQualityInfluencerAggregate interface.
 */
export function instanceOfBetPredictionQualityInfluencerAggregate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetPredictionQualityInfluencerAggregateFromJSON(json: any): BetPredictionQualityInfluencerAggregate {
    return BetPredictionQualityInfluencerAggregateFromJSONTyped(json, false);
}

export function BetPredictionQualityInfluencerAggregateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetPredictionQualityInfluencerAggregate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'influencerName': !exists(json, 'influencerName') ? undefined : json['influencerName'],
        'predictionPercent': !exists(json, 'predictionPercent') ? undefined : json['predictionPercent'],
        'betSucceeded': !exists(json, 'betSucceeded') ? undefined : json['betSucceeded'],
        'betFailed': !exists(json, 'betFailed') ? undefined : json['betFailed'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function BetPredictionQualityInfluencerAggregateToJSON(value?: BetPredictionQualityInfluencerAggregate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'influencerName': value.influencerName,
        'predictionPercent': value.predictionPercent,
        'betSucceeded': value.betSucceeded,
        'betFailed': value.betFailed,
        'count': value.count,
    };
}

