/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExceptionResponse
 */
export interface ExceptionResponse {
    /**
     * 
     * @type {string}
     * @memberof ExceptionResponse
     */
    eXCEPTIONRESPONSE?: string;
    /**
     * 
     * @type {string}
     * @memberof ExceptionResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the ExceptionResponse interface.
 */
export function instanceOfExceptionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExceptionResponseFromJSON(json: any): ExceptionResponse {
    return ExceptionResponseFromJSONTyped(json, false);
}

export function ExceptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExceptionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eXCEPTIONRESPONSE': !exists(json, 'EXCEPTION_RESPONSE') ? undefined : json['EXCEPTION_RESPONSE'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ExceptionResponseToJSON(value?: ExceptionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EXCEPTION_RESPONSE': value.eXCEPTIONRESPONSE,
        'id': value.id,
    };
}

