/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Ranking } from './Ranking';
import {
    RankingFromJSON,
    RankingFromJSONTyped,
    RankingToJSON,
} from './Ranking';

/**
 * 
 * @export
 * @interface InfluencerStatisticalResultOutcome
 */
export interface InfluencerStatisticalResultOutcome {
    /**
     * 
     * @type {string}
     * @memberof InfluencerStatisticalResultOutcome
     */
    influencerName?: string;
    /**
     * 
     * @type {number}
     * @memberof InfluencerStatisticalResultOutcome
     */
    statisticalOutcomeBetSuccess?: number;
    /**
     * 
     * @type {Ranking}
     * @memberof InfluencerStatisticalResultOutcome
     */
    ranking?: Ranking;
}

/**
 * Check if a given object implements the InfluencerStatisticalResultOutcome interface.
 */
export function instanceOfInfluencerStatisticalResultOutcome(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfluencerStatisticalResultOutcomeFromJSON(json: any): InfluencerStatisticalResultOutcome {
    return InfluencerStatisticalResultOutcomeFromJSONTyped(json, false);
}

export function InfluencerStatisticalResultOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfluencerStatisticalResultOutcome {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'influencerName': !exists(json, 'influencerName') ? undefined : json['influencerName'],
        'statisticalOutcomeBetSuccess': !exists(json, 'statisticalOutcomeBetSuccess') ? undefined : json['statisticalOutcomeBetSuccess'],
        'ranking': !exists(json, 'ranking') ? undefined : RankingFromJSON(json['ranking']),
    };
}

export function InfluencerStatisticalResultOutcomeToJSON(value?: InfluencerStatisticalResultOutcome | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'influencerName': value.influencerName,
        'statisticalOutcomeBetSuccess': value.statisticalOutcomeBetSuccess,
        'ranking': RankingToJSON(value.ranking),
    };
}

