/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfluencerResult
 */
export interface InfluencerResult {
    /**
     * 
     * @type {string}
     * @memberof InfluencerResult
     */
    influencerName?: string;
    /**
     * 
     * @type {number}
     * @memberof InfluencerResult
     */
    influencerPredictionValue?: number;
    /**
     * 
     * @type {string}
     * @memberof InfluencerResult
     */
    precheckResult?: InfluencerResultPrecheckResultEnum;
}


/**
 * @export
 */
export const InfluencerResultPrecheckResultEnum = {
    NotEnoughInformation: 'NOT_ENOUGH_INFORMATION',
    DontKnowWhatToCalculateForBet: 'DONT_KNOW_WHAT_TO_CALCULATE_FOR_BET',
    InvalidStats: 'INVALID_STATS',
    Exception: 'EXCEPTION',
    Ok: 'OK'
} as const;
export type InfluencerResultPrecheckResultEnum = typeof InfluencerResultPrecheckResultEnum[keyof typeof InfluencerResultPrecheckResultEnum];


/**
 * Check if a given object implements the InfluencerResult interface.
 */
export function instanceOfInfluencerResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfluencerResultFromJSON(json: any): InfluencerResult {
    return InfluencerResultFromJSONTyped(json, false);
}

export function InfluencerResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfluencerResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'influencerName': !exists(json, 'influencerName') ? undefined : json['influencerName'],
        'influencerPredictionValue': !exists(json, 'influencerPredictionValue') ? undefined : json['influencerPredictionValue'],
        'precheckResult': !exists(json, 'precheckResult') ? undefined : json['precheckResult'],
    };
}

export function InfluencerResultToJSON(value?: InfluencerResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'influencerName': value.influencerName,
        'influencerPredictionValue': value.influencerPredictionValue,
        'precheckResult': value.precheckResult,
    };
}

