/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PredictionQualityRevision } from './PredictionQualityRevision';
import {
    PredictionQualityRevisionFromJSON,
    PredictionQualityRevisionFromJSONTyped,
    PredictionQualityRevisionToJSON,
} from './PredictionQualityRevision';
import type { PredictionResult } from './PredictionResult';
import {
    PredictionResultFromJSON,
    PredictionResultFromJSONTyped,
    PredictionResultToJSON,
} from './PredictionResult';
import type { StatisticalResultOutcome } from './StatisticalResultOutcome';
import {
    StatisticalResultOutcomeFromJSON,
    StatisticalResultOutcomeFromJSONTyped,
    StatisticalResultOutcomeToJSON,
} from './StatisticalResultOutcome';

/**
 * 
 * @export
 * @interface MatchListElement
 */
export interface MatchListElement {
    /**
     * 
     * @type {number}
     * @memberof MatchListElement
     */
    dateUnix?: number;
    /**
     * 
     * @type {Date}
     * @memberof MatchListElement
     */
    dateGMT?: Date;
    /**
     * 
     * @type {string}
     * @memberof MatchListElement
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchListElement
     */
    league?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchListElement
     */
    homeTeam?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchListElement
     */
    awayTeam?: string;
    /**
     * 
     * @type {number}
     * @memberof MatchListElement
     */
    goalsHomeTeam?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchListElement
     */
    goalsAwayTeam?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchListElement
     */
    state?: MatchListElementStateEnum;
    /**
     * 
     * @type {string}
     * @memberof MatchListElement
     */
    footyStatsUrl?: string;
    /**
     * 
     * @type {PredictionResult}
     * @memberof MatchListElement
     */
    o05?: PredictionResult;
    /**
     * 
     * @type {PredictionResult}
     * @memberof MatchListElement
     */
    bttsYes?: PredictionResult;
    /**
     * 
     * @type {PredictionQualityRevision}
     * @memberof MatchListElement
     */
    revision?: PredictionQualityRevision;
    /**
     * 
     * @type {Array<StatisticalResultOutcome>}
     * @memberof MatchListElement
     */
    statisticalResultOutcome?: Array<StatisticalResultOutcome>;
}


/**
 * @export
 */
export const MatchListElementStateEnum = {
    Complete: 'complete',
    Incomplete: 'incomplete',
    Suspended: 'suspended',
    Canceled: 'canceled'
} as const;
export type MatchListElementStateEnum = typeof MatchListElementStateEnum[keyof typeof MatchListElementStateEnum];


/**
 * Check if a given object implements the MatchListElement interface.
 */
export function instanceOfMatchListElement(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MatchListElementFromJSON(json: any): MatchListElement {
    return MatchListElementFromJSONTyped(json, false);
}

export function MatchListElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchListElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateUnix': !exists(json, 'dateUnix') ? undefined : json['dateUnix'],
        'dateGMT': !exists(json, 'dateGMT') ? undefined : (new Date(json['dateGMT'])),
        'country': !exists(json, 'country') ? undefined : json['country'],
        'league': !exists(json, 'league') ? undefined : json['league'],
        'homeTeam': !exists(json, 'homeTeam') ? undefined : json['homeTeam'],
        'awayTeam': !exists(json, 'awayTeam') ? undefined : json['awayTeam'],
        'goalsHomeTeam': !exists(json, 'goalsHomeTeam') ? undefined : json['goalsHomeTeam'],
        'goalsAwayTeam': !exists(json, 'goalsAwayTeam') ? undefined : json['goalsAwayTeam'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'footyStatsUrl': !exists(json, 'footyStatsUrl') ? undefined : json['footyStatsUrl'],
        'o05': !exists(json, 'o05') ? undefined : PredictionResultFromJSON(json['o05']),
        'bttsYes': !exists(json, 'bttsYes') ? undefined : PredictionResultFromJSON(json['bttsYes']),
        'revision': !exists(json, 'revision') ? undefined : PredictionQualityRevisionFromJSON(json['revision']),
        'statisticalResultOutcome': !exists(json, 'statisticalResultOutcome') ? undefined : ((json['statisticalResultOutcome'] as Array<any>).map(StatisticalResultOutcomeFromJSON)),
    };
}

export function MatchListElementToJSON(value?: MatchListElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateUnix': value.dateUnix,
        'dateGMT': value.dateGMT === undefined ? undefined : (value.dateGMT.toISOString()),
        'country': value.country,
        'league': value.league,
        'homeTeam': value.homeTeam,
        'awayTeam': value.awayTeam,
        'goalsHomeTeam': value.goalsHomeTeam,
        'goalsAwayTeam': value.goalsAwayTeam,
        'state': value.state,
        'footyStatsUrl': value.footyStatsUrl,
        'o05': PredictionResultToJSON(value.o05),
        'bttsYes': PredictionResultToJSON(value.bttsYes),
        'revision': PredictionQualityRevisionToJSON(value.revision),
        'statisticalResultOutcome': value.statisticalResultOutcome === undefined ? undefined : ((value.statisticalResultOutcome as Array<any>).map(StatisticalResultOutcomeToJSON)),
    };
}

