/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchStats
 */
export interface MatchStats {
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    dateUnix?: number;
    /**
     * 
     * @type {Date}
     * @memberof MatchStats
     */
    dateGmt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MatchStats
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchStats
     */
    league?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchStats
     */
    homeTeam?: string;
    /**
     * 
     * @type {string}
     * @memberof MatchStats
     */
    awayTeam?: string;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamPointsPerGamePreMatch?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamPointsPerGamePreMatch?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamPointsPerGameCurrent?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamPointsPerGameCurrent?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    averageGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over05Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over15Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over25Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over35Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over45Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over05FHGHTAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over15FHGHTAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over052HGAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    over152HGAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    averageCorners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    averageCards?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    averageOver8dot5Corners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    averageOver9dot5Corners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    averageOver10dot5Corners?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchStats
     */
    matchStatus?: MatchStatsMatchStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    resultHomeTeamGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    resultAwayTeamGoals?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamCorners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamCorners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamOffsides?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamOffsides?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamYellowCards?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamYellowCards?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamRedCards?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamRedCards?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamShots?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamShots?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamShotsOnTarget?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamShotsOnTarget?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamShotsOffTarget?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamShotsOffTarget?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamPossession?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamPossession?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsHomeWin?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsDraw?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsAwayWin?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsOver15?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsOver25?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsOver35?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsOver45?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsBTTSYes?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsBTTSNo?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamPreMatchxG?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamPreMatchxG?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamxG?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamxG?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsUnder05?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsUnder15?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsUnder25?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsUnder35?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsUnder45?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsDoubleChance1x?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsDoubleChance12?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsDoubleChancex2?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsDrawNoBet1?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsDrawNoBet2?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersOver75?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersOver85?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersOver95?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersOver105?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersOver115?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersUnder75?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersUnder85?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersUnder95?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersUnder105?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsCornersUnder115?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    under05Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    under15Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    under25Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    under35Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    under45Average?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfOver05?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfOver15?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfOver25?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfUnder05?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfUnder15?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfUnder25?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfOver05?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfOver15?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfOver25?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfUnder05?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfUnder15?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfUnder25?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfBTTSYes?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds1stHalfBTTSNo?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfBTTSYes?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    odds2ndHalfBTTSNo?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    firstHBTTSAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsHomeTeamHadMoreCorners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsBothTeamsSameCorners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    oddsAwayTeamHadMoreCorners?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    homeTeamOverallPointsPerGamePreMatch?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    awayTeamOverallPointsPerGamePreMatch?: number;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    gameWeek?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchStats
     */
    matchFootyStatsURL?: string;
    /**
     * 
     * @type {number}
     * @memberof MatchStats
     */
    bttsaverage?: number;
}

/**
* @export
* @enum {string}
*/
export enum MatchStatsMatchStatusEnum {
    Complete = 'complete',
    Incomplete = 'incomplete',
    Suspended = 'suspended',
    Canceled = 'canceled'
}

export function MatchStatsFromJSON(json: any): MatchStats {
    return MatchStatsFromJSONTyped(json, false);
}

export function MatchStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateUnix': !exists(json, 'dateUnix') ? undefined : json['dateUnix'],
        'dateGmt': !exists(json, 'dateGmt') ? undefined : (new Date(json['dateGmt'])),
        'country': !exists(json, 'country') ? undefined : json['country'],
        'league': !exists(json, 'league') ? undefined : json['league'],
        'homeTeam': !exists(json, 'homeTeam') ? undefined : json['homeTeam'],
        'awayTeam': !exists(json, 'awayTeam') ? undefined : json['awayTeam'],
        'homeTeamPointsPerGamePreMatch': !exists(json, 'homeTeamPointsPerGamePreMatch') ? undefined : json['homeTeamPointsPerGamePreMatch'],
        'awayTeamPointsPerGamePreMatch': !exists(json, 'awayTeamPointsPerGamePreMatch') ? undefined : json['awayTeamPointsPerGamePreMatch'],
        'homeTeamPointsPerGameCurrent': !exists(json, 'homeTeamPointsPerGameCurrent') ? undefined : json['homeTeamPointsPerGameCurrent'],
        'awayTeamPointsPerGameCurrent': !exists(json, 'awayTeamPointsPerGameCurrent') ? undefined : json['awayTeamPointsPerGameCurrent'],
        'averageGoals': !exists(json, 'averageGoals') ? undefined : json['averageGoals'],
        'over05Average': !exists(json, 'over05Average') ? undefined : json['over05Average'],
        'over15Average': !exists(json, 'over15Average') ? undefined : json['over15Average'],
        'over25Average': !exists(json, 'over25Average') ? undefined : json['over25Average'],
        'over35Average': !exists(json, 'over35Average') ? undefined : json['over35Average'],
        'over45Average': !exists(json, 'over45Average') ? undefined : json['over45Average'],
        'over05FHGHTAverage': !exists(json, 'over05FHGHTAverage') ? undefined : json['over05FHGHTAverage'],
        'over15FHGHTAverage': !exists(json, 'over15FHGHTAverage') ? undefined : json['over15FHGHTAverage'],
        'over052HGAverage': !exists(json, 'over052HGAverage') ? undefined : json['over052HGAverage'],
        'over152HGAverage': !exists(json, 'over152HGAverage') ? undefined : json['over152HGAverage'],
        'averageCorners': !exists(json, 'averageCorners') ? undefined : json['averageCorners'],
        'averageCards': !exists(json, 'averageCards') ? undefined : json['averageCards'],
        'averageOver8dot5Corners': !exists(json, 'averageOver8dot5Corners') ? undefined : json['averageOver8dot5Corners'],
        'averageOver9dot5Corners': !exists(json, 'averageOver9dot5Corners') ? undefined : json['averageOver9dot5Corners'],
        'averageOver10dot5Corners': !exists(json, 'averageOver10dot5Corners') ? undefined : json['averageOver10dot5Corners'],
        'matchStatus': !exists(json, 'matchStatus') ? undefined : json['matchStatus'],
        'resultHomeTeamGoals': !exists(json, 'resultHomeTeamGoals') ? undefined : json['resultHomeTeamGoals'],
        'resultAwayTeamGoals': !exists(json, 'resultAwayTeamGoals') ? undefined : json['resultAwayTeamGoals'],
        'homeTeamCorners': !exists(json, 'homeTeamCorners') ? undefined : json['homeTeamCorners'],
        'awayTeamCorners': !exists(json, 'awayTeamCorners') ? undefined : json['awayTeamCorners'],
        'homeTeamOffsides': !exists(json, 'homeTeamOffsides') ? undefined : json['homeTeamOffsides'],
        'awayTeamOffsides': !exists(json, 'awayTeamOffsides') ? undefined : json['awayTeamOffsides'],
        'homeTeamYellowCards': !exists(json, 'homeTeamYellowCards') ? undefined : json['homeTeamYellowCards'],
        'awayTeamYellowCards': !exists(json, 'awayTeamYellowCards') ? undefined : json['awayTeamYellowCards'],
        'homeTeamRedCards': !exists(json, 'homeTeamRedCards') ? undefined : json['homeTeamRedCards'],
        'awayTeamRedCards': !exists(json, 'awayTeamRedCards') ? undefined : json['awayTeamRedCards'],
        'homeTeamShots': !exists(json, 'homeTeamShots') ? undefined : json['homeTeamShots'],
        'awayTeamShots': !exists(json, 'awayTeamShots') ? undefined : json['awayTeamShots'],
        'homeTeamShotsOnTarget': !exists(json, 'homeTeamShotsOnTarget') ? undefined : json['homeTeamShotsOnTarget'],
        'awayTeamShotsOnTarget': !exists(json, 'awayTeamShotsOnTarget') ? undefined : json['awayTeamShotsOnTarget'],
        'homeTeamShotsOffTarget': !exists(json, 'homeTeamShotsOffTarget') ? undefined : json['homeTeamShotsOffTarget'],
        'awayTeamShotsOffTarget': !exists(json, 'awayTeamShotsOffTarget') ? undefined : json['awayTeamShotsOffTarget'],
        'homeTeamPossession': !exists(json, 'homeTeamPossession') ? undefined : json['homeTeamPossession'],
        'awayTeamPossession': !exists(json, 'awayTeamPossession') ? undefined : json['awayTeamPossession'],
        'oddsHomeWin': !exists(json, 'oddsHomeWin') ? undefined : json['oddsHomeWin'],
        'oddsDraw': !exists(json, 'oddsDraw') ? undefined : json['oddsDraw'],
        'oddsAwayWin': !exists(json, 'oddsAwayWin') ? undefined : json['oddsAwayWin'],
        'oddsOver15': !exists(json, 'oddsOver15') ? undefined : json['oddsOver15'],
        'oddsOver25': !exists(json, 'oddsOver25') ? undefined : json['oddsOver25'],
        'oddsOver35': !exists(json, 'oddsOver35') ? undefined : json['oddsOver35'],
        'oddsOver45': !exists(json, 'oddsOver45') ? undefined : json['oddsOver45'],
        'oddsBTTSYes': !exists(json, 'oddsBTTS_Yes') ? undefined : json['oddsBTTS_Yes'],
        'oddsBTTSNo': !exists(json, 'oddsBTTS_No') ? undefined : json['oddsBTTS_No'],
        'homeTeamPreMatchxG': !exists(json, 'homeTeamPreMatchxG') ? undefined : json['homeTeamPreMatchxG'],
        'awayTeamPreMatchxG': !exists(json, 'awayTeamPreMatchxG') ? undefined : json['awayTeamPreMatchxG'],
        'homeTeamxG': !exists(json, 'homeTeamxG') ? undefined : json['homeTeamxG'],
        'awayTeamxG': !exists(json, 'awayTeamxG') ? undefined : json['awayTeamxG'],
        'oddsUnder05': !exists(json, 'oddsUnder05') ? undefined : json['oddsUnder05'],
        'oddsUnder15': !exists(json, 'oddsUnder15') ? undefined : json['oddsUnder15'],
        'oddsUnder25': !exists(json, 'oddsUnder25') ? undefined : json['oddsUnder25'],
        'oddsUnder35': !exists(json, 'oddsUnder35') ? undefined : json['oddsUnder35'],
        'oddsUnder45': !exists(json, 'oddsUnder45') ? undefined : json['oddsUnder45'],
        'oddsDoubleChance1x': !exists(json, 'oddsDoubleChance1x') ? undefined : json['oddsDoubleChance1x'],
        'oddsDoubleChance12': !exists(json, 'oddsDoubleChance12') ? undefined : json['oddsDoubleChance12'],
        'oddsDoubleChancex2': !exists(json, 'oddsDoubleChancex2') ? undefined : json['oddsDoubleChancex2'],
        'oddsDrawNoBet1': !exists(json, 'oddsDrawNoBet1') ? undefined : json['oddsDrawNoBet1'],
        'oddsDrawNoBet2': !exists(json, 'oddsDrawNoBet2') ? undefined : json['oddsDrawNoBet2'],
        'oddsCornersOver75': !exists(json, 'oddsCornersOver75') ? undefined : json['oddsCornersOver75'],
        'oddsCornersOver85': !exists(json, 'oddsCornersOver85') ? undefined : json['oddsCornersOver85'],
        'oddsCornersOver95': !exists(json, 'oddsCornersOver95') ? undefined : json['oddsCornersOver95'],
        'oddsCornersOver105': !exists(json, 'oddsCornersOver105') ? undefined : json['oddsCornersOver105'],
        'oddsCornersOver115': !exists(json, 'oddsCornersOver115') ? undefined : json['oddsCornersOver115'],
        'oddsCornersUnder75': !exists(json, 'oddsCornersUnder75') ? undefined : json['oddsCornersUnder75'],
        'oddsCornersUnder85': !exists(json, 'oddsCornersUnder85') ? undefined : json['oddsCornersUnder85'],
        'oddsCornersUnder95': !exists(json, 'oddsCornersUnder95') ? undefined : json['oddsCornersUnder95'],
        'oddsCornersUnder105': !exists(json, 'oddsCornersUnder105') ? undefined : json['oddsCornersUnder105'],
        'oddsCornersUnder115': !exists(json, 'oddsCornersUnder115') ? undefined : json['oddsCornersUnder115'],
        'under05Average': !exists(json, 'under05Average') ? undefined : json['under05Average'],
        'under15Average': !exists(json, 'under15Average') ? undefined : json['under15Average'],
        'under25Average': !exists(json, 'under25Average') ? undefined : json['under25Average'],
        'under35Average': !exists(json, 'under35Average') ? undefined : json['under35Average'],
        'under45Average': !exists(json, 'under45Average') ? undefined : json['under45Average'],
        'odds1stHalfOver05': !exists(json, 'odds1stHalfOver05') ? undefined : json['odds1stHalfOver05'],
        'odds1stHalfOver15': !exists(json, 'odds1stHalfOver15') ? undefined : json['odds1stHalfOver15'],
        'odds1stHalfOver25': !exists(json, 'odds1stHalfOver25') ? undefined : json['odds1stHalfOver25'],
        'odds1stHalfUnder05': !exists(json, 'odds1stHalfUnder05') ? undefined : json['odds1stHalfUnder05'],
        'odds1stHalfUnder15': !exists(json, 'odds1stHalfUnder15') ? undefined : json['odds1stHalfUnder15'],
        'odds1stHalfUnder25': !exists(json, 'odds1stHalfUnder25') ? undefined : json['odds1stHalfUnder25'],
        'odds2ndHalfOver05': !exists(json, 'odds2ndHalfOver05') ? undefined : json['odds2ndHalfOver05'],
        'odds2ndHalfOver15': !exists(json, 'odds2ndHalfOver15') ? undefined : json['odds2ndHalfOver15'],
        'odds2ndHalfOver25': !exists(json, 'odds2ndHalfOver25') ? undefined : json['odds2ndHalfOver25'],
        'odds2ndHalfUnder05': !exists(json, 'odds2ndHalfUnder05') ? undefined : json['odds2ndHalfUnder05'],
        'odds2ndHalfUnder15': !exists(json, 'odds2ndHalfUnder15') ? undefined : json['odds2ndHalfUnder15'],
        'odds2ndHalfUnder25': !exists(json, 'odds2ndHalfUnder25') ? undefined : json['odds2ndHalfUnder25'],
        'odds1stHalfBTTSYes': !exists(json, 'odds1stHalfBTTS_Yes') ? undefined : json['odds1stHalfBTTS_Yes'],
        'odds1stHalfBTTSNo': !exists(json, 'odds1stHalfBTTS_No') ? undefined : json['odds1stHalfBTTS_No'],
        'odds2ndHalfBTTSYes': !exists(json, 'odds2ndHalfBTTS_Yes') ? undefined : json['odds2ndHalfBTTS_Yes'],
        'odds2ndHalfBTTSNo': !exists(json, 'odds2ndHalfBTTS_No') ? undefined : json['odds2ndHalfBTTS_No'],
        'firstHBTTSAverage': !exists(json, 'firstHBTTSAverage') ? undefined : json['firstHBTTSAverage'],
        'oddsHomeTeamHadMoreCorners': !exists(json, 'oddsHomeTeamHadMoreCorners') ? undefined : json['oddsHomeTeamHadMoreCorners'],
        'oddsBothTeamsSameCorners': !exists(json, 'oddsBothTeamsSameCorners') ? undefined : json['oddsBothTeamsSameCorners'],
        'oddsAwayTeamHadMoreCorners': !exists(json, 'oddsAwayTeamHadMoreCorners') ? undefined : json['oddsAwayTeamHadMoreCorners'],
        'homeTeamOverallPointsPerGamePreMatch': !exists(json, 'homeTeamOverallPointsPerGamePreMatch') ? undefined : json['homeTeamOverallPointsPerGamePreMatch'],
        'awayTeamOverallPointsPerGamePreMatch': !exists(json, 'awayTeamOverallPointsPerGamePreMatch') ? undefined : json['awayTeamOverallPointsPerGamePreMatch'],
        'gameWeek': !exists(json, 'gameWeek') ? undefined : json['gameWeek'],
        'matchFootyStatsURL': !exists(json, 'matchFootyStatsURL') ? undefined : json['matchFootyStatsURL'],
        'bttsaverage': !exists(json, 'bttsaverage') ? undefined : json['bttsaverage'],
    };
}

export function MatchStatsToJSON(value?: MatchStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateUnix': value.dateUnix,
        'dateGmt': value.dateGmt === undefined ? undefined : (value.dateGmt.toISOString()),
        'country': value.country,
        'league': value.league,
        'homeTeam': value.homeTeam,
        'awayTeam': value.awayTeam,
        'homeTeamPointsPerGamePreMatch': value.homeTeamPointsPerGamePreMatch,
        'awayTeamPointsPerGamePreMatch': value.awayTeamPointsPerGamePreMatch,
        'homeTeamPointsPerGameCurrent': value.homeTeamPointsPerGameCurrent,
        'awayTeamPointsPerGameCurrent': value.awayTeamPointsPerGameCurrent,
        'averageGoals': value.averageGoals,
        'over05Average': value.over05Average,
        'over15Average': value.over15Average,
        'over25Average': value.over25Average,
        'over35Average': value.over35Average,
        'over45Average': value.over45Average,
        'over05FHGHTAverage': value.over05FHGHTAverage,
        'over15FHGHTAverage': value.over15FHGHTAverage,
        'over052HGAverage': value.over052HGAverage,
        'over152HGAverage': value.over152HGAverage,
        'averageCorners': value.averageCorners,
        'averageCards': value.averageCards,
        'averageOver8dot5Corners': value.averageOver8dot5Corners,
        'averageOver9dot5Corners': value.averageOver9dot5Corners,
        'averageOver10dot5Corners': value.averageOver10dot5Corners,
        'matchStatus': value.matchStatus,
        'resultHomeTeamGoals': value.resultHomeTeamGoals,
        'resultAwayTeamGoals': value.resultAwayTeamGoals,
        'homeTeamCorners': value.homeTeamCorners,
        'awayTeamCorners': value.awayTeamCorners,
        'homeTeamOffsides': value.homeTeamOffsides,
        'awayTeamOffsides': value.awayTeamOffsides,
        'homeTeamYellowCards': value.homeTeamYellowCards,
        'awayTeamYellowCards': value.awayTeamYellowCards,
        'homeTeamRedCards': value.homeTeamRedCards,
        'awayTeamRedCards': value.awayTeamRedCards,
        'homeTeamShots': value.homeTeamShots,
        'awayTeamShots': value.awayTeamShots,
        'homeTeamShotsOnTarget': value.homeTeamShotsOnTarget,
        'awayTeamShotsOnTarget': value.awayTeamShotsOnTarget,
        'homeTeamShotsOffTarget': value.homeTeamShotsOffTarget,
        'awayTeamShotsOffTarget': value.awayTeamShotsOffTarget,
        'homeTeamPossession': value.homeTeamPossession,
        'awayTeamPossession': value.awayTeamPossession,
        'oddsHomeWin': value.oddsHomeWin,
        'oddsDraw': value.oddsDraw,
        'oddsAwayWin': value.oddsAwayWin,
        'oddsOver15': value.oddsOver15,
        'oddsOver25': value.oddsOver25,
        'oddsOver35': value.oddsOver35,
        'oddsOver45': value.oddsOver45,
        'oddsBTTS_Yes': value.oddsBTTSYes,
        'oddsBTTS_No': value.oddsBTTSNo,
        'homeTeamPreMatchxG': value.homeTeamPreMatchxG,
        'awayTeamPreMatchxG': value.awayTeamPreMatchxG,
        'homeTeamxG': value.homeTeamxG,
        'awayTeamxG': value.awayTeamxG,
        'oddsUnder05': value.oddsUnder05,
        'oddsUnder15': value.oddsUnder15,
        'oddsUnder25': value.oddsUnder25,
        'oddsUnder35': value.oddsUnder35,
        'oddsUnder45': value.oddsUnder45,
        'oddsDoubleChance1x': value.oddsDoubleChance1x,
        'oddsDoubleChance12': value.oddsDoubleChance12,
        'oddsDoubleChancex2': value.oddsDoubleChancex2,
        'oddsDrawNoBet1': value.oddsDrawNoBet1,
        'oddsDrawNoBet2': value.oddsDrawNoBet2,
        'oddsCornersOver75': value.oddsCornersOver75,
        'oddsCornersOver85': value.oddsCornersOver85,
        'oddsCornersOver95': value.oddsCornersOver95,
        'oddsCornersOver105': value.oddsCornersOver105,
        'oddsCornersOver115': value.oddsCornersOver115,
        'oddsCornersUnder75': value.oddsCornersUnder75,
        'oddsCornersUnder85': value.oddsCornersUnder85,
        'oddsCornersUnder95': value.oddsCornersUnder95,
        'oddsCornersUnder105': value.oddsCornersUnder105,
        'oddsCornersUnder115': value.oddsCornersUnder115,
        'under05Average': value.under05Average,
        'under15Average': value.under15Average,
        'under25Average': value.under25Average,
        'under35Average': value.under35Average,
        'under45Average': value.under45Average,
        'odds1stHalfOver05': value.odds1stHalfOver05,
        'odds1stHalfOver15': value.odds1stHalfOver15,
        'odds1stHalfOver25': value.odds1stHalfOver25,
        'odds1stHalfUnder05': value.odds1stHalfUnder05,
        'odds1stHalfUnder15': value.odds1stHalfUnder15,
        'odds1stHalfUnder25': value.odds1stHalfUnder25,
        'odds2ndHalfOver05': value.odds2ndHalfOver05,
        'odds2ndHalfOver15': value.odds2ndHalfOver15,
        'odds2ndHalfOver25': value.odds2ndHalfOver25,
        'odds2ndHalfUnder05': value.odds2ndHalfUnder05,
        'odds2ndHalfUnder15': value.odds2ndHalfUnder15,
        'odds2ndHalfUnder25': value.odds2ndHalfUnder25,
        'odds1stHalfBTTS_Yes': value.odds1stHalfBTTSYes,
        'odds1stHalfBTTS_No': value.odds1stHalfBTTSNo,
        'odds2ndHalfBTTS_Yes': value.odds2ndHalfBTTSYes,
        'odds2ndHalfBTTS_No': value.odds2ndHalfBTTSNo,
        'firstHBTTSAverage': value.firstHBTTSAverage,
        'oddsHomeTeamHadMoreCorners': value.oddsHomeTeamHadMoreCorners,
        'oddsBothTeamsSameCorners': value.oddsBothTeamsSameCorners,
        'oddsAwayTeamHadMoreCorners': value.oddsAwayTeamHadMoreCorners,
        'homeTeamOverallPointsPerGamePreMatch': value.homeTeamOverallPointsPerGamePreMatch,
        'awayTeamOverallPointsPerGamePreMatch': value.awayTeamOverallPointsPerGamePreMatch,
        'gameWeek': value.gameWeek,
        'matchFootyStatsURL': value.matchFootyStatsURL,
        'bttsaverage': value.bttsaverage,
    };
}

