/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectId
 */
export interface ObjectId {
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    timestamp?: number;
    /**
     * 
     * @type {Date}
     * @memberof ObjectId
     */
    date?: Date;
}

/**
 * Check if a given object implements the ObjectId interface.
 */
export function instanceOfObjectId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ObjectIdFromJSON(json: any): ObjectId {
    return ObjectIdFromJSONTyped(json, false);
}

export function ObjectIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
    };
}

export function ObjectIdToJSON(value?: ObjectId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
    };
}

