/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Match,
    MatchFromJSON,
    MatchFromJSONTyped,
    MatchToJSON,
} from './Match';

/**
 * 
 * @export
 * @interface PagingResponseMatch
 */
export interface PagingResponseMatch {
    /**
     * 
     * @type {number}
     * @memberof PagingResponseMatch
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagingResponseMatch
     */
    totalElements?: number;
    /**
     * 
     * @type {Array<Match>}
     * @memberof PagingResponseMatch
     */
    elements?: Array<Match>;
}

export function PagingResponseMatchFromJSON(json: any): PagingResponseMatch {
    return PagingResponseMatchFromJSONTyped(json, false);
}

export function PagingResponseMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagingResponseMatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'elements': !exists(json, 'elements') ? undefined : ((json['elements'] as Array<any>).map(MatchFromJSON)),
    };
}

export function PagingResponseMatchToJSON(value?: PagingResponseMatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'elements': value.elements === undefined ? undefined : ((value.elements as Array<any>).map(MatchToJSON)),
    };
}

