/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Paging
 */
export interface Paging {
    /**
     * 
     * @type {number}
     * @memberof Paging
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof Paging
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof Paging
     */
    direction?: PagingDirectionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Paging
     */
    properties?: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum PagingDirectionEnum {
    Asc = 'ASC',
    Desc = 'DESC'
}

export function PagingFromJSON(json: any): Paging {
    return PagingFromJSONTyped(json, false);
}

export function PagingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Paging {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
    };
}

export function PagingToJSON(value?: Paging | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'size': value.size,
        'direction': value.direction,
        'properties': value.properties,
    };
}

