/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MatchListElement } from './MatchListElement';
import {
    MatchListElementFromJSON,
    MatchListElementFromJSONTyped,
    MatchListElementToJSON,
} from './MatchListElement';

/**
 * 
 * @export
 * @interface PagingResponseMatchListElement
 */
export interface PagingResponseMatchListElement {
    /**
     * 
     * @type {number}
     * @memberof PagingResponseMatchListElement
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagingResponseMatchListElement
     */
    totalElements?: number;
    /**
     * 
     * @type {Array<MatchListElement>}
     * @memberof PagingResponseMatchListElement
     */
    elements?: Array<MatchListElement>;
}

/**
 * Check if a given object implements the PagingResponseMatchListElement interface.
 */
export function instanceOfPagingResponseMatchListElement(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagingResponseMatchListElementFromJSON(json: any): PagingResponseMatchListElement {
    return PagingResponseMatchListElementFromJSONTyped(json, false);
}

export function PagingResponseMatchListElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagingResponseMatchListElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalElements': !exists(json, 'totalElements') ? undefined : json['totalElements'],
        'elements': !exists(json, 'elements') ? undefined : ((json['elements'] as Array<any>).map(MatchListElementFromJSON)),
    };
}

export function PagingResponseMatchListElementToJSON(value?: PagingResponseMatchListElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPages': value.totalPages,
        'totalElements': value.totalElements,
        'elements': value.elements === undefined ? undefined : ((value.elements as Array<any>).map(MatchListElementToJSON)),
    };
}

