/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictionQualityRevision
 */
export interface PredictionQualityRevision {
    /**
     * 
     * @type {number}
     * @memberof PredictionQualityRevision
     */
    revision?: number;
}

/**
 * Check if a given object implements the PredictionQualityRevision interface.
 */
export function instanceOfPredictionQualityRevision(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PredictionQualityRevisionFromJSON(json: any): PredictionQualityRevision {
    return PredictionQualityRevisionFromJSONTyped(json, false);
}

export function PredictionQualityRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionQualityRevision {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'revision': !exists(json, 'revision') ? undefined : json['revision'],
    };
}

export function PredictionQualityRevisionToJSON(value?: PredictionQualityRevision | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'revision': value.revision,
    };
}

