/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetPredictionQualityAllBetsAggregate } from './BetPredictionQualityAllBetsAggregate';
import {
    BetPredictionQualityAllBetsAggregateFromJSON,
    BetPredictionQualityAllBetsAggregateFromJSONTyped,
    BetPredictionQualityAllBetsAggregateToJSON,
} from './BetPredictionQualityAllBetsAggregate';
import type { BetPredictionQualityBetAggregate } from './BetPredictionQualityBetAggregate';
import {
    BetPredictionQualityBetAggregateFromJSON,
    BetPredictionQualityBetAggregateFromJSONTyped,
    BetPredictionQualityBetAggregateToJSON,
} from './BetPredictionQualityBetAggregate';
import type { BetPredictionQualityInfluencerAggregate } from './BetPredictionQualityInfluencerAggregate';
import {
    BetPredictionQualityInfluencerAggregateFromJSON,
    BetPredictionQualityInfluencerAggregateFromJSONTyped,
    BetPredictionQualityInfluencerAggregateToJSON,
} from './BetPredictionQualityInfluencerAggregate';

/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {Array<BetPredictionQualityAllBetsAggregate>}
     * @memberof Report
     */
    betPredictionResults?: Array<BetPredictionQualityAllBetsAggregate>;
    /**
     * 
     * @type {Array<BetPredictionQualityBetAggregate>}
     * @memberof Report
     */
    betPredictionDistributions?: Array<BetPredictionQualityBetAggregate>;
    /**
     * 
     * @type {Array<BetPredictionQualityBetAggregate>}
     * @memberof Report
     */
    dontBetPredictionDistributions?: Array<BetPredictionQualityBetAggregate>;
    /**
     * 
     * @type {{ [key: string]: Array<BetPredictionQualityInfluencerAggregate>; }}
     * @memberof Report
     */
    betInfluencerPercentDistributions?: { [key: string]: Array<BetPredictionQualityInfluencerAggregate>; };
    /**
     * 
     * @type {{ [key: string]: Array<BetPredictionQualityInfluencerAggregate>; }}
     * @memberof Report
     */
    dontBetInfluencerPercentDistributions?: { [key: string]: Array<BetPredictionQualityInfluencerAggregate>; };
}

/**
 * Check if a given object implements the Report interface.
 */
export function instanceOfReport(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReportFromJSON(json: any): Report {
    return ReportFromJSONTyped(json, false);
}

export function ReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): Report {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'betPredictionResults': !exists(json, 'betPredictionResults') ? undefined : ((json['betPredictionResults'] as Array<any>).map(BetPredictionQualityAllBetsAggregateFromJSON)),
        'betPredictionDistributions': !exists(json, 'betPredictionDistributions') ? undefined : ((json['betPredictionDistributions'] as Array<any>).map(BetPredictionQualityBetAggregateFromJSON)),
        'dontBetPredictionDistributions': !exists(json, 'dontBetPredictionDistributions') ? undefined : ((json['dontBetPredictionDistributions'] as Array<any>).map(BetPredictionQualityBetAggregateFromJSON)),
        'betInfluencerPercentDistributions': !exists(json, 'betInfluencerPercentDistributions') ? undefined : json['betInfluencerPercentDistributions'],
        'dontBetInfluencerPercentDistributions': !exists(json, 'dontBetInfluencerPercentDistributions') ? undefined : json['dontBetInfluencerPercentDistributions'],
    };
}

export function ReportToJSON(value?: Report | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'betPredictionResults': value.betPredictionResults === undefined ? undefined : ((value.betPredictionResults as Array<any>).map(BetPredictionQualityAllBetsAggregateToJSON)),
        'betPredictionDistributions': value.betPredictionDistributions === undefined ? undefined : ((value.betPredictionDistributions as Array<any>).map(BetPredictionQualityBetAggregateToJSON)),
        'dontBetPredictionDistributions': value.dontBetPredictionDistributions === undefined ? undefined : ((value.dontBetPredictionDistributions as Array<any>).map(BetPredictionQualityBetAggregateToJSON)),
        'betInfluencerPercentDistributions': value.betInfluencerPercentDistributions,
        'dontBetInfluencerPercentDistributions': value.dontBetInfluencerPercentDistributions,
    };
}

