/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InfluencerStatisticalResultOutcome } from './InfluencerStatisticalResultOutcome';
import {
    InfluencerStatisticalResultOutcomeFromJSON,
    InfluencerStatisticalResultOutcomeFromJSONTyped,
    InfluencerStatisticalResultOutcomeToJSON,
} from './InfluencerStatisticalResultOutcome';
import type { Ranking } from './Ranking';
import {
    RankingFromJSON,
    RankingFromJSONTyped,
    RankingToJSON,
} from './Ranking';

/**
 * 
 * @export
 * @interface StatisticalResultOutcome
 */
export interface StatisticalResultOutcome {
    /**
     * 
     * @type {string}
     * @memberof StatisticalResultOutcome
     */
    bet?: StatisticalResultOutcomeBetEnum;
    /**
     * 
     * @type {number}
     * @memberof StatisticalResultOutcome
     */
    betStatisticalSuccess?: number;
    /**
     * 
     * @type {Ranking}
     * @memberof StatisticalResultOutcome
     */
    ranking?: Ranking;
    /**
     * 
     * @type {Array<InfluencerStatisticalResultOutcome>}
     * @memberof StatisticalResultOutcome
     */
    influencerStatisticalResultOutcomes?: Array<InfluencerStatisticalResultOutcome>;
}


/**
 * @export
 */
export const StatisticalResultOutcomeBetEnum = {
    OverZeroFive: 'OVER_ZERO_FIVE',
    OverOneFive: 'OVER_ONE_FIVE',
    BttsYes: 'BTTS_YES',
    BttsNo: 'BTTS_NO'
} as const;
export type StatisticalResultOutcomeBetEnum = typeof StatisticalResultOutcomeBetEnum[keyof typeof StatisticalResultOutcomeBetEnum];


/**
 * Check if a given object implements the StatisticalResultOutcome interface.
 */
export function instanceOfStatisticalResultOutcome(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StatisticalResultOutcomeFromJSON(json: any): StatisticalResultOutcome {
    return StatisticalResultOutcomeFromJSONTyped(json, false);
}

export function StatisticalResultOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatisticalResultOutcome {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bet': !exists(json, 'bet') ? undefined : json['bet'],
        'betStatisticalSuccess': !exists(json, 'betStatisticalSuccess') ? undefined : json['betStatisticalSuccess'],
        'ranking': !exists(json, 'ranking') ? undefined : RankingFromJSON(json['ranking']),
        'influencerStatisticalResultOutcomes': !exists(json, 'influencerStatisticalResultOutcomes') ? undefined : ((json['influencerStatisticalResultOutcomes'] as Array<any>).map(InfluencerStatisticalResultOutcomeFromJSON)),
    };
}

export function StatisticalResultOutcomeToJSON(value?: StatisticalResultOutcome | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bet': value.bet,
        'betStatisticalSuccess': value.betStatisticalSuccess,
        'ranking': RankingToJSON(value.ranking),
        'influencerStatisticalResultOutcomes': value.influencerStatisticalResultOutcomes === undefined ? undefined : ((value.influencerStatisticalResultOutcomes as Array<any>).map(InfluencerStatisticalResultOutcomeToJSON)),
    };
}

