/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ExceptionResponse,
  LiveAndHotMatches,
} from '../models';
import {
    ExceptionResponseFromJSON,
    ExceptionResponseToJSON,
    LiveAndHotMatchesFromJSON,
    LiveAndHotMatchesToJSON,
} from '../models';

/**
 * 
 */
export class LiveAndHotControllerApi extends runtime.BaseAPI {

    /**
     */
    async listRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LiveAndHotMatches>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/match/liveandhot`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LiveAndHotMatchesFromJSON));
    }

    /**
     */
    async list(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LiveAndHotMatches>> {
        const response = await this.listRaw(initOverrides);
        return await response.value();
    }

}
