/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    MatchStats,
    MatchStatsFromJSON,
    MatchStatsToJSON,
} from '../models';

export interface FindByCountryRequest {
    country: string;
}

/**
 * 
 */
export class MatchStatsControllerApi extends runtime.BaseAPI {

    /**
     */
    async findByCountryRaw(requestParameters: FindByCountryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<MatchStats>>> {
        if (requestParameters.country === null || requestParameters.country === undefined) {
            throw new runtime.RequiredError('country','Required parameter requestParameters.country was null or undefined when calling findByCountry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/matchstats/{country}`.replace(`{${"country"}}`, encodeURIComponent(String(requestParameters.country))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MatchStatsFromJSON));
    }

    /**
     */
    async findByCountry(requestParameters: FindByCountryRequest, initOverrides?: RequestInit): Promise<Array<MatchStats>> {
        const response = await this.findByCountryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
